import { useState, useEffect, useRef } from 'react';
import { useWizard } from '../../contexts/ProjectWizardContext';
import axios from 'axios';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Loader2, Send, FileText, Clock, CheckCircle2, XCircle } from 'lucide-react';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3001/api';

export default function StepSendRFQs() {
  const { projectId, selectedVendorIds } = useWizard();
  const [rfqs, setRfqs] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [sending, setSending] = useState<string | null>(null);
  const [sendingAll, setSendingAll] = useState(false);
  const autoGenerated = useRef(false);

  useEffect(() => {
    if (projectId) loadData();
  }, [projectId]);

  const loadData = async () => {
    setLoading(true);
    try {
      const rfqRes = await axios.get(`${API_URL}/rfq?projectId=${projectId}`);
      const existing = rfqRes.data || [];
      setRfqs(existing);

      // Auto-generate RFQs if none exist yet
      if (existing.length === 0 && !autoGenerated.current) {
        autoGenerated.current = true;
        await autoCreateRFQs();
      }
    } catch (err) {
      console.error('Failed to load RFQ data:', err);
    } finally {
      setLoading(false);
    }
  };

  const autoCreateRFQs = async () => {
    try {
      // Get vendor IDs: prefer context (set in step 4), fall back to backend
      let vendorIds = selectedVendorIds || [];
      if (vendorIds.length === 0) {
        try {
          const vendorsRes = await axios.get(`${API_URL}/projects/${projectId}/selected-vendors`);
          vendorIds = (vendorsRes.data?.vendors || []).map((v: any) => v.id);
        } catch { /* continue */ }
      }

      const bomRes = await axios.get(`${API_URL}/bom?projectId=${projectId}`);
      const bomItems = bomRes.data?.items || [];
      const materialIds = bomItems.map((item: any) => item.id);

      if (vendorIds.length === 0 || materialIds.length === 0) return;

      for (const vendorId of vendorIds) {
        try {
          await axios.post(`${API_URL}/rfq/create`, {
            projectId,
            vendorId,
            materialIds,
          });
        } catch { /* individual RFQ creation may fail */ }
      }

      // Reload after creation
      const rfqRes = await axios.get(`${API_URL}/rfq?projectId=${projectId}`);
      setRfqs(rfqRes.data || []);
    } catch (err) {
      console.error('Failed to auto-create RFQs:', err);
    }
  };

  const sendRFQ = async (rfqId: string) => {
    setSending(rfqId);
    try {
      await axios.post(`${API_URL}/rfq/${rfqId}/send`);
      loadData();
    } catch (err) {
      console.error('Failed to send RFQ:', err);
    } finally {
      setSending(null);
    }
  };

  const sendAllDrafts = async () => {
    const drafts = rfqs.filter((r: any) => r.status === 'DRAFT');
    if (drafts.length === 0) return;

    setSendingAll(true);
    try {
      for (const rfq of drafts) {
        try {
          await axios.post(`${API_URL}/rfq/${rfq.id}/send`);
        } catch { /* continue with others */ }
      }
      loadData();
    } finally {
      setSendingAll(false);
    }
  };

  const downloadPDF = async (rfqId: string, rfqNumber: string) => {
    try {
      const response = await axios.get(`${API_URL}/rfq/${rfqId}/pdf`, { responseType: 'blob' });
      const url = window.URL.createObjectURL(new Blob([response.data], { type: 'application/pdf' }));
      const link = document.createElement('a');
      link.href = url;
      link.download = `${rfqNumber}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
    } catch {
      // PDF download may not be available
    }
  };

  const statusIcon = (status: string) => {
    switch (status) {
      case 'DRAFT': return <Clock className="w-4 h-4 text-yellow-600" />;
      case 'SENT': return <Send className="w-4 h-4 text-blue-600" />;
      case 'RESPONDED': return <CheckCircle2 className="w-4 h-4 text-green-600" />;
      default: return <XCircle className="w-4 h-4 text-gray-400" />;
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-16">
        <div className="text-center">
          <Loader2 className="w-8 h-8 animate-spin text-muted-foreground mx-auto mb-4" />
          <p className="text-sm text-muted-foreground">Generating RFQs for your selected vendors...</p>
        </div>
      </div>
    );
  }

  if (!projectId) {
    return <div className="text-center py-16 text-muted-foreground">Complete previous steps first</div>;
  }

  const drafts = rfqs.filter((r: any) => r.status === 'DRAFT');
  const sent = rfqs.filter((r: any) => r.status === 'SENT');
  const responded = rfqs.filter((r: any) => r.status === 'RESPONDED');

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">Review RFQs</h2>
          <p className="text-muted-foreground">
            {rfqs.length} RFQs generated for your selected vendors — review and send
          </p>
        </div>
        {drafts.length > 0 && (
          <Button onClick={sendAllDrafts} disabled={sendingAll}>
            {sendingAll ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Send className="w-4 h-4 mr-2" />}
            Send All ({drafts.length})
          </Button>
        )}
      </div>

      {/* Stats */}
      <div className="grid grid-cols-4 gap-4">
        <Card>
          <CardContent className="pt-6">
            <div className="text-2xl font-bold">{rfqs.length}</div>
            <p className="text-xs text-muted-foreground">Total RFQs</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-2xl font-bold">{drafts.length}</div>
            <p className="text-xs text-muted-foreground">Ready to Send</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-2xl font-bold">{sent.length}</div>
            <p className="text-xs text-muted-foreground">Sent</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-2xl font-bold">{responded.length}</div>
            <p className="text-xs text-muted-foreground">Responded</p>
          </CardContent>
        </Card>
      </div>

      {/* RFQ Table */}
      <Card>
        <CardHeader>
          <CardTitle>Requests for Quotes</CardTitle>
          <CardDescription>
            Each RFQ includes your full BOM for the vendor to price
          </CardDescription>
        </CardHeader>
        <CardContent>
          {rfqs.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              <FileText className="w-16 h-16 mx-auto mb-4 opacity-50" />
              <p>No RFQs could be generated.</p>
              <p className="text-sm mt-1">Go back and select vendors in the previous step.</p>
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>RFQ Number</TableHead>
                  <TableHead>Vendor</TableHead>
                  <TableHead>Items</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Sent Date</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {rfqs.map((rfq: any) => (
                  <TableRow key={rfq.id}>
                    <TableCell className="font-mono text-sm">{rfq.rfqNumber}</TableCell>
                    <TableCell className="font-medium">{rfq.vendor?.name || 'Unknown'}</TableCell>
                    <TableCell>{rfq._count?.items || 0} items</TableCell>
                    <TableCell>
                      <Badge
                        variant={rfq.status === 'SENT' ? 'default' : rfq.status === 'RESPONDED' ? 'default' : 'secondary'}
                        className="gap-1"
                      >
                        {statusIcon(rfq.status)} {rfq.status}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-sm text-muted-foreground">
                      {rfq.sentAt ? new Date(rfq.sentAt).toLocaleDateString() : '-'}
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex gap-2 justify-end">
                        <Button size="sm" variant="ghost" onClick={() => downloadPDF(rfq.id, rfq.rfqNumber)}>
                          <FileText className="w-4 h-4 mr-1" /> PDF
                        </Button>
                        {rfq.status === 'DRAFT' && (
                          <Button
                            size="sm"
                            onClick={() => sendRFQ(rfq.id)}
                            disabled={sending === rfq.id}
                          >
                            {sending === rfq.id ? (
                              <Loader2 className="w-4 h-4 mr-1 animate-spin" />
                            ) : (
                              <Send className="w-4 h-4 mr-1" />
                            )}
                            Send
                          </Button>
                        )}
                        {rfq.status === 'SENT' && (
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => sendRFQ(rfq.id)}
                            disabled={sending === rfq.id}
                          >
                            {sending === rfq.id ? (
                              <Loader2 className="w-4 h-4 mr-1 animate-spin" />
                            ) : (
                              <Send className="w-4 h-4 mr-1" />
                            )}
                            Resend
                          </Button>
                        )}
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
